import sqlite3
conn=sqlite3.connect('univ.db')
cur=conn.cursor()
#name=input('Enter name: ')
#city=input('Enter city: ')
#Deptno=int(input('Enter department no: '))
#cur.execute('create table Dept(Deptno integer primary key,dname text)')
#cur.execute('create table Student(roll integer primary key,name text,city text,Deptno integer,foreign key(Deptno) references Dept(Deptno))')
#cur.execute('insert into Dept values(40,"Mech")')
#cur.execute('insert into  Student(name, city, Deptno) values (?, ?, ?)', (name, city, Deptno))
#row=cur.execute('select name from Student where city in (select city from Student where name="Verma")')
#row=cur.execute('update Student set city="Bhopal" where roll=15')
row=cur.execute('delete from Student where roll=15')
print(row.fetchall())
conn.commit()
cur.close()
conn.close()