import sqlite3
conn=sqlite3.connect('shop.db')
cur=conn.cursor()
OrderNo=input("Enter order no:")
CId=input('Enter customer id:')
PId=input('Enter product id:')
Qty=int(input('Enter product quantity:'))
#cur.execute('create table Customer(CId Text Primary Key,Cname Text,Address Text)')
#cur.execute('create table Product(PId Text Primary Key,Pname Text,Price Integer)')
#cur.execute('create table "Order"(OrderNo integer ,CId Text,PId Text,Qty integer,foreign key(CId) references Customer(CId),foreign key(PId) references Product(PId))')
#cur.execute('insert into Customer(CID,Cname,Address) values(?,?,?)',(CId,Cname,Address))
cur.execute('insert into "Order"(OrderNo,CId,PId,Qty) values(?,?,?,?)',(OrderNo,CId,PId,Qty))
conn.commit()
cur.close()
conn.close()